title: KalaStatic
description: Static site framework for prototyping and building out CMS-less websites at Kalamuna.
copyright: Copyright © 2015 <a href="http://kalamuna.com">Kalamuna, Inc</a>. All Rights Reserved.
